import Fastify from 'fastify';import cookie from '@fastify/cookie';import cors from '@fastify/cors';import { prisma } from './db/prisma.js';import { hashPassword, verifyPassword } from './auth/password.js';import { getSession, setSession } from './auth/session.js';import { Role } from '@prisma/client';import { nanoid } from 'nanoid';import crypto from 'crypto';
const app=Fastify(); app.register(cookie); app.register(cors,{origin:true,credentials:true});
const requireAuth=async(req:any,rep:any)=>{const s=getSession(req); if(!s) return rep.code(401).send({error:'unauthorized'}); req.session=s;};
const requireChannel=async(req:any,rep:any,role:Role='viewer')=>{const c=String(req.params.channelId); const r=req.session.channelRoles[c] as Role|undefined; if(!(r&&(['system_owner','platform_admin'].includes(req.session.role)||['viewer','channel_moderator','channel_admin','channel_owner'].indexOf(r)>=['viewer','channel_moderator','channel_admin','channel_owner'].indexOf(role)))) return rep.code(403).send({error:'forbidden'});};
app.get('/api/setup/status', async()=>({setupAllowed:!(await prisma.channelMember.findFirst({where:{role:'system_owner'}}))}));
app.post('/api/setup/create-owner', async(req:any,rep)=>{const exists=await prisma.channelMember.findFirst({where:{role:'system_owner'}}); if(exists) return rep.code(403).send({error:'setup disabled'}); const b=req.body; const user=await prisma.user.create({data:{email:b.email,passwordHash:await hashPassword(b.password),displayName:b.displayName,isLocalAdmin:true}}); await prisma.channel.create({data:{twitchChannelId:`sys-${user.id}`,twitchLogin:'system',displayName:'System'}}).then(c=>prisma.channelMember.create({data:{channelId:c.id,userId:user.id,role:'system_owner'}})); setSession(rep,{id:user.id,role:'system_owner',channelRoles:{}}); return {ok:true};});
app.post('/api/auth/login', async(req:any,rep)=>{const {email,password}=req.body;const u=await prisma.user.findUnique({where:{email}}); if(!u?.passwordHash||!(await verifyPassword(u.passwordHash,password)))return rep.code(401).send({error:'invalid'}); const m=await prisma.channelMember.findMany({where:{userId:u.id}}); const cr=Object.fromEntries(m.map(x=>[x.channelId,x.role])); const role=(m.find(x=>x.role==='system_owner')?.role||m.find(x=>x.role==='platform_admin')?.role||'viewer') as string; setSession(rep,{id:u.id,role,channelRoles:cr}); return {ok:true};});
app.post('/api/auth/logout', async(_req,rep)=>{rep.clearCookie('sf_session'); return {ok:true};});
app.get('/api/auth/me',{preHandler:requireAuth},async(req:any)=>({session:req.session}));
app.get('/api/channels',{preHandler:requireAuth},async(req:any)=>prisma.channel.findMany({where:['system_owner','platform_admin'].includes(req.session.role)?{}:{id:{in:Object.keys(req.session.channelRoles)}}}));
app.post('/api/channels',{preHandler:requireAuth},async(req:any,rep)=>{if(!['system_owner','platform_admin'].includes(req.session.role))return rep.code(403).send({error:'forbidden'});const b=req.body;const c=await prisma.channel.create({data:{twitchChannelId:b.twitchChannelId,twitchLogin:b.twitchLogin,displayName:b.displayName,commands:{create:{name:'ping',aliasesJson:'[]',response:'pong',requiredRole:'viewer'}},settings:{create:{}}}});return c;});
app.get('/api/channels/:channelId',{preHandler:requireAuth},async(req:any,rep)=>{await requireChannel(req,rep); return prisma.channel.findUnique({where:{id:req.params.channelId}});});
app.patch('/api/channels/:channelId',{preHandler:requireAuth},async(req:any,rep)=>{await requireChannel(req,rep,'channel_admin'); return prisma.channel.update({where:{id:req.params.channelId},data:req.body});});
app.delete('/api/channels/:channelId',{preHandler:requireAuth},async(req:any,rep)=>{await requireChannel(req,rep,'channel_owner'); await prisma.channel.delete({where:{id:req.params.channelId}}); return {ok:true};});
for (const ent of ['commands','timers','campaigns'] as const){app.get(`/api/channels/:channelId/${ent}`,{preHandler:requireAuth},async(req:any,rep)=>{await requireChannel(req,rep); return (prisma as any)[ent.slice(0,-1)].findMany({where:{channelId:req.params.channelId}});});}
app.get('/c/:shortCode', async(req:any,rep)=>{const c=await prisma.campaign.findUnique({where:{shortCode:req.params.shortCode}}); if(!c)return rep.code(404).send('not found'); await prisma.campaignClick.create({data:{campaignId:c.id,platform:'twitch',ipHash:crypto.createHash('sha256').update(req.ip).digest('hex')}}); rep.redirect(c.targetUrl);});
app.get('/api/admin/health',{preHandler:requireAuth},async(req:any,rep)=>{if(!['system_owner','platform_admin'].includes(req.session.role))return rep.code(403).send({error:'forbidden'}); return {ok:true};});
export default app;
