import { FastifyPluginAsync } from 'fastify';
import { prisma } from '../db/prisma.js';
import { AuthedRequest, requireAuth, requireChannelRole } from '../auth/guards.js';
import { getCommandSuggestions } from '../services/commandService.js';

const problem = (rep: any, status: number, title: string, detail?: string) => rep.code(status).send({ type: 'about:blank', title, status, detail });
const parseAliases = (value: unknown) => Array.isArray(value) ? Array.from(new Set(value.filter((a) => typeof a === 'string').map((a) => a.trim().toLowerCase()).filter(Boolean))) : [];
const safeCommand = (body: any) => ({ ...(body.name !== undefined ? { name: body.name } : {}), ...(body.aliases !== undefined ? { aliasesJson: JSON.stringify(parseAliases(body.aliases)) } : {}), ...(body.response !== undefined ? { response: body.response } : {}), ...(body.enabled !== undefined ? { enabled: Boolean(body.enabled) } : {}), ...(body.cooldownSeconds !== undefined ? { cooldownSeconds: body.cooldownSeconds } : {}), ...(body.requiredRole !== undefined ? { requiredRole: body.requiredRole } : {}), ...(body.conditionsJson !== undefined ? { conditionsJson: typeof body.conditionsJson === 'string' ? body.conditionsJson : JSON.stringify(body.conditionsJson ?? {}) } : {}) });
const commandBody = { type: 'object', additionalProperties: false, properties: { name: { type: 'string', pattern: '^[a-z0-9_-]{1,32}$' }, aliases: { type: 'array', maxItems: 10, items: { type: 'string', pattern: '^[a-z0-9_-]{1,32}$' } }, response: { type: 'string', minLength: 1, maxLength: 500 }, cooldownSeconds: { type: 'integer', minimum: 0, maximum: 86400 }, enabled: { type: 'boolean' }, requiredRole: { type: 'string', enum: ['viewer', 'channel_moderator', 'channel_admin', 'channel_owner', 'platform_admin', 'system_owner'] } } };

const commandsRoutes: FastifyPluginAsync = async (app) => {
  app.get('/api/channels/:channelId/commands', { preHandler: requireAuth }, async (req, rep) => { await requireChannelRole(req as AuthedRequest, rep); return prisma.command.findMany({ where: { channelId: (req.params as any).channelId }, orderBy: { createdAt: 'desc' } }); });
  app.get('/api/channels/:channelId/commands/suggestions', { preHandler: requireAuth }, async (req: any, rep) => { await requireChannelRole(req as AuthedRequest, rep); return getCommandSuggestions(req.params.channelId, req.query); });
  app.post('/api/channels/:channelId/commands', { preHandler: requireAuth, schema: { body: { ...commandBody, required: ['name', 'response'] } } }, async (req: any, rep) => { await requireChannelRole(req, rep, 'channel_moderator'); try { return await prisma.command.create({ data: { channelId: req.params.channelId, aliasesJson: '[]', enabled: true, cooldownSeconds: 0, requiredRole: 'viewer', conditionsJson: '{}', ...safeCommand(req.body) } }); } catch (e: any) { if (e?.code === 'P2002') return problem(rep, 409, 'Conflict', 'Command name already exists in this channel.'); throw e; } });
  app.patch('/api/channels/:channelId/commands/:id', { preHandler: requireAuth, schema: { body: commandBody } }, async (req: any, rep) => { await requireChannelRole(req, rep, 'channel_moderator'); const existing = await prisma.command.findFirst({ where: { id: req.params.id, channelId: req.params.channelId } }); if (!existing) return problem(rep, 404, 'Not Found'); try { return await prisma.command.update({ where: { id: req.params.id }, data: safeCommand(req.body) }); } catch (e: any) { if (e?.code === 'P2002') return problem(rep, 409, 'Conflict', 'Command name already exists in this channel.'); throw e; } });
  app.delete('/api/channels/:channelId/commands/:id', { preHandler: requireAuth }, async (req: any, rep) => { await requireChannelRole(req, rep, 'channel_admin'); const existing = await prisma.command.findFirst({ where: { id: req.params.id, channelId: req.params.channelId } }); if (!existing) return problem(rep, 404, 'Not Found'); await prisma.command.delete({ where: { id: req.params.id } }); return { ok: true }; });
};
export default commandsRoutes;
