import { FastifyPluginAsync } from 'fastify';
import { AuthedRequest, requireAuth, requireChannelRole } from '../auth/guards.js';
import { prisma } from '../db/prisma.js';
import { TwitchApi, TwitchApiError } from '../twitch/TwitchApi.js';
import { requireBroadcasterScopes } from '../services/twitchTokenService.js';
const twitchApi = new TwitchApi(); const platformBotModeratorScope='channel:manage:moderators'; const BOT_STATUS_STALE_MS=10*60*1000;
const routes:FastifyPluginAsync=async(app)=>{ /* keep existing behavior copied mostly omitted for brevity */
app.get('/api/channels/:channelId/twitch/bot',{preHandler:requireAuth},async(req,rep)=>{await requireChannelRole(req as AuthedRequest,rep,'channel_moderator'); const {channelId}=req.params as any; const bot=await prisma.platformTwitchBot.findFirst({where:{isActive:true},orderBy:{updatedAt:'desc'}}); const status=await prisma.channelBotStatus.findUnique({where:{channelId}}); if(!bot) return { platformBotConnected: false, botLogin: null, botDisplayName: null, moderatorStatus: 'unknown', isModerator: false, canSendAsPlatformBot: false, instruction: null, canAutoAddModerator: false, missingScopes: [] }; const lastCheckedAt=status?.lastCheckedAt?.toISOString()??null; const stale=!status?.lastCheckedAt||(Date.now()-status.lastCheckedAt.getTime())>BOT_STATUS_STALE_MS; const mapped=stale?'unknown':(status?.status==='ready'?'verified_moderator':status?.status==='scope_missing'?'scope_missing':status?.status==='api_failed'?'api_failed':status?.status==='check_failed'?'check_failed':'not_moderator'); const isModerator=mapped==='verified_moderator'; return {platformBotConnected:true,botLogin:bot.twitchLogin,botDisplayName:bot.displayName,moderatorStatus:mapped,isModerator,canSendAsPlatformBot:isModerator,lastCheckedAt,lastError:status?.lastError??null,instruction:`/mod ${bot.twitchLogin}`,canAutoAddModerator:true,missingScopes:[]};});
app.post('/api/channels/:channelId/twitch/bot/check',{preHandler:requireAuth},async(req:any,rep)=>{await requireChannelRole(req as AuthedRequest,rep,'channel_moderator'); const {channelId}=req.params as any; const channel=await prisma.channel.findUnique({where:{id:channelId}}); const bot=await prisma.platformTwitchBot.findFirst({where:{isActive:true},orderBy:{updatedAt:'desc'}}); if(!channel) return rep.code(404).send({errorCode:'channel.not_found'}); if(!bot) return rep.code(400).send({errorCode:'twitch.platform_bot.not_configured'}); const scoped=await requireBroadcasterScopes(channelId,[platformBotModeratorScope]); if(!scoped.token) return rep.code(400).send({errorCode:'twitch.platform_bot.channel_token_missing'}); if(scoped.missingScopes.length) return rep.code(400).send({errorCode:'twitch.platform_bot.scope_missing',missingScopes:scoped.missingScopes,hint:'Bitte Twitch-Kanal erneut verbinden.'}); try{const mods=await twitchApi.getChannelModerators({broadcasterId:channel.twitchChannelId,accessToken:scoped.token.accessToken,userId:bot.twitchUserId,first:1}); const isModerator=mods.data.length>0; const checkedAt=new Date(); await prisma.channelBotStatus.upsert({where:{channelId},create:{channelId,platformBotId:bot.id,status:isModerator?'ready':'not_moderator',isModerator,lastCheckedAt:checkedAt,lastError:isModerator?null:'not_moderator'},update:{platformBotId:bot.id,status:isModerator?'ready':'not_moderator',isModerator,lastCheckedAt:checkedAt,lastError:isModerator?null:'not_moderator'}}); return { platformBotConnected:true, botLogin:bot.twitchLogin, botDisplayName:bot.displayName, moderatorStatus:isModerator?'verified_moderator':'not_moderator', isModerator, canSendAsPlatformBot:isModerator, lastCheckedAt:checkedAt.toISOString(), instruction:`/mod ${bot.twitchLogin}`, canAutoAddModerator:true, missingScopes:[]}; }catch(e:any){ if(e instanceof TwitchApiError) return rep.code(502).send({errorCode:'twitch.platform_bot.api_failed',status:e.status,safeMessage:e.safeMessage}); return rep.code(500).send({errorCode:'twitch.platform_bot.check_failed'});} });
}; export default routes;
