import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiGet } from '../api/client';
import Card from '../components/ui/Card';
import LoadingState from '../components/ui/LoadingState';
import ErrorBox from '../components/ui/ErrorBox';
import PageHeader from '../components/ui/PageHeader';

export default function DashboardHome(){const {channelId=''}=useParams(); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [s,setS]=useState<any>({});
useEffect(()=>{const load=async()=>{setLoading(true);setError('');try{const [commands,timers,logs,channel,health,chats,chatters]=await Promise.all([apiGet<any[]>(`/api/channels/${channelId}/commands`).catch(()=>[]),apiGet<any[]>(`/api/channels/${channelId}/timers`).catch(()=>[]),apiGet<{items:any[]}>(`/api/channels/${channelId}/logs?limit=5`).catch(()=>({items:[]})),apiGet<any>(`/api/channels/${channelId}`).catch(()=>null),apiGet<any>('/api/admin/health').catch(()=>null),apiGet<any>(`/api/channels/${channelId}/chat/messages?limit=1`).catch(()=>({items:[]})),apiGet<any>(`/api/channels/${channelId}/twitch/chatters?limit=1`).catch((e:any)=>({errorCode:e?.data?.errorCode,total:null}))]); setS({commandCount:commands.length,timerCount:timers.length,lastChat:chats.items?.[0]?.createdAt??logs.items.find((i)=>i.eventType?.includes('chat'))?.createdAt??null,botEvents:logs.items,botEnabled:channel?.botEnabled,eventSubEnabled:health?.twitch?.eventSubEnabled,channelActive:channel?.isActive,chatterCount:chatters.total,chattersScopeMissing:chatters.errorCode==='twitch.chatters.missing_scope'});}catch(e:any){setError(e?.data?.detail??'Übersicht konnte nicht geladen werden.');}finally{setLoading(false);}}; void load();},[channelId]);
return <div className='space-y-4'><PageHeader title='Dashboard Übersicht' subtitle='Produktionsnahe Live-Übersicht für den ausgewählten Channel.'/>{loading&&<LoadingState label='Lade Übersicht…'/>}{error&&<ErrorBox message={error}/>}<div className='grid md:grid-cols-3 gap-3'><Card className='p-3'>Channel aktiv: <b>{s.channelActive===undefined?'Noch keine Daten':s.channelActive?'Ja':'Nein'}</b></Card><Card className='p-3'>Bot enabled: <b>{s.botEnabled===undefined?'Noch keine Daten':s.botEnabled?'Ja':'Nein'}</b></Card><Card className='p-3'>EventSub: <b>{s.eventSubEnabled===undefined?'Noch keine Daten':s.eventSubEnabled?'Aktiv':'Inaktiv'}</b></Card><Card className='p-3'>Commands: <b>{s.commandCount ?? 0}</b></Card><Card className='p-3'>Timer: <b>{s.timerCount ?? 0}</b></Card><Card className='p-3'>Letzte Chatnachricht: <b>{s.lastChat?new Date(s.lastChat).toLocaleString():'Noch keine Daten'}</b></Card><Card className='p-3'>Aktuelle Chatter: <b>{s.chatterCount ?? 'n/a'}</b>{s.chattersScopeMissing&&<div className='text-xs text-amber-400 mt-1'>Twitch erneut verbinden</div>}</Card></div><Card className='p-3'><div className='font-semibold mb-2'>Letzte BotEvents</div>{!s.botEvents?.length?<div className='text-sm text-slate-400'>Noch keine Daten</div>:s.botEvents.map((e:any)=><div key={e.id} className='text-sm border-t border-zinc-800 py-1'>{new Date(e.createdAt).toLocaleString()} · {e.eventType}</div>)}</Card><Card className='p-3'><div className='font-semibold mb-2'>Quick Actions</div><div className='flex gap-2 flex-wrap'><Link className='rounded bg-indigo-600 px-3 py-2 text-sm' to={`/dashboard/channels/${channelId}/live-chat`}>Live Chat</Link><Link className='rounded bg-indigo-600 px-3 py-2 text-sm' to={`/dashboard/channels/${channelId}/chatters`}>Chatters</Link><Link className='rounded bg-zinc-700 px-3 py-2 text-sm' to={`/dashboard/channels/${channelId}/commands`}>Command erstellen</Link></div></Card></div>}
