import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import { apiGet } from '../api/client';
import Card from '../components/ui/Card';
import EmptyState from '../components/ui/EmptyState';
import ErrorBox from '../components/ui/ErrorBox';
import LoadingState from '../components/ui/LoadingState';
import PageHeader from '../components/ui/PageHeader';

type LogItem={id:string;createdAt:string;eventType:string;platform:string;payloadJson:string};
export default function LogsPage(){const {channelId=''}=useParams(); const [items,setItems]=useState<LogItem[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [eventType,setEventType]=useState(''); const [platform,setPlatform]=useState(''); const [limit,setLimit]=useState(100);
const load=async()=>{setLoading(true);setError('');try{const q=new URLSearchParams({limit:String(limit)}); if(eventType)q.set('eventType',eventType); if(platform)q.set('platform',platform); const res=await apiGet<{items:LogItem[]}>(`/api/channels/${channelId}/logs?${q.toString()}`); setItems(res.items);}catch(e:any){setError(e?.data?.detail??e?.data?.error??'Logs konnten nicht geladen werden.');}finally{setLoading(false);}}; useEffect(()=>{void load();},[channelId]);
return <div className='space-y-4'><PageHeader title='Logs' subtitle='Bot- und Channel-Events für den Betrieb nachvollziehen.'/><Card className='p-4 flex gap-2 flex-wrap'><input className='bg-zinc-900 border border-zinc-700 rounded px-2 py-1' placeholder='eventType' value={eventType} onChange={(e)=>setEventType(e.target.value)}/><select className='bg-zinc-900 border border-zinc-700 rounded px-2 py-1' value={platform} onChange={(e)=>setPlatform(e.target.value)}><option value=''>alle Plattformen</option><option value='twitch'>twitch</option></select><input className='bg-zinc-900 border border-zinc-700 rounded px-2 py-1 w-24' type='number' value={limit} min={1} max={500} onChange={(e)=>setLimit(Number(e.target.value))}/><button className='rounded bg-indigo-600 px-3 py-1' onClick={()=>void load()}>Filter anwenden</button></Card>{error&&<ErrorBox message={error}/>}{loading?<LoadingState label='Logs laden…'/>:items.length===0?<EmptyState title='Keine Logs vorhanden' description='Für die gewählten Filter wurden keine BotEvents gefunden.'/>:<Card className='p-0 overflow-x-auto'><table className='w-full text-sm'><thead><tr><th className='p-2 text-left'>Zeit</th><th className='p-2 text-left'>Event Type</th><th className='p-2 text-left'>Platform</th><th className='p-2 text-left'>Kurzbeschreibung</th><th className='p-2 text-left'>Details</th></tr></thead><tbody>{items.map((it)=><tr key={it.id} className='border-t border-zinc-800'><td className='p-2'>{new Date(it.createdAt).toLocaleString()}</td><td className='p-2'>{it.eventType}</td><td className='p-2'>{it.platform}</td><td className='p-2'>{it.eventType.replace(/_/g,' ')}</td><td className='p-2'><details><summary>anzeigen</summary><pre className='whitespace-pre-wrap text-xs'>{it.payloadJson?.replace(/(token|secret|authorization)\s*:\s*"[^"]+"/gi,'$1:"***"')}</pre></details></td></tr>)}</tbody></table></Card>}</div>}
