import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { apiGet, apiPost } from '../api/client';
import Card from '../components/ui/Card';
import ConfirmDialog from '../components/ui/ConfirmDialog';
import EmptyState from '../components/ui/EmptyState';
import ErrorBox from '../components/ui/ErrorBox';
import LoadingState from '../components/ui/LoadingState';
import PageHeader from '../components/ui/PageHeader';
import StatusBadge from '../components/ui/StatusBadge';

export default function ModerationPage() { const { channelId = '' } = useParams(); const [items,setItems]=useState<any[]>([]); const [actions,setActions]=useState<any[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [ok,setOk]=useState(''); const [confirmOpen,setConfirmOpen]=useState(false); const [form,setForm]=useState<any>({ userId:'', username:'', action:'timeout', durationSeconds:300, reason:'' });
  const load = async()=>{ setLoading(true); try { const [bans,log]=await Promise.all([apiGet<any>(`/api/channels/${channelId}/moderation/bans?limit=100`),apiGet<any>(`/api/channels/${channelId}/moderation/actions?limit=50`)]); setItems(bans.items||[]); setActions(log.actions||[]); setError(''); } catch(e:any){ setError(e?.data?.errorCode==='twitch.moderation.scope_missing'?'Bitte Twitch erneut verbinden.':(e?.data?.hint||e?.data?.errorCode||'Fehler')); } finally { setLoading(false);} };
  useEffect(()=>{void load();},[channelId]);
  const submit = async()=>{ if(!form.userId && !form.username){setError('User erforderlich.'); return;} if(form.action==='timeout' && !Number(form.durationSeconds)){setError('Timeout-Dauer erforderlich.'); return;} if((form.reason||'').length>500){setError('Grund maximal 500 Zeichen.'); return;} setConfirmOpen(true); };
  const run = async()=>{ const path=form.action==='unban'?'unban':form.action; const body:any={userId:form.userId||undefined,username:form.username||undefined,reason:form.reason||undefined}; if(form.action==='timeout') body.durationSeconds=Number(form.durationSeconds); try{await apiPost(`/api/channels/${channelId}/moderation/${path}`,body); setOk('Moderationsaktion erfolgreich ausgeführt.'); setError(''); await load();}catch(e:any){setError(e?.data?.errorCode||'Aktion fehlgeschlagen.');}};
  const active = useMemo(()=>items.filter((x:any)=>!x.expiresAt || new Date(x.expiresAt).getTime()>Date.now()),[items]);
  return <div className='space-y-4'><PageHeader title='Moderation' subtitle='Arbeitsbereich für aktive Maßnahmen und Moderationsaktionen.' />{loading&&<LoadingState label='Moderation wird geladen…'/>}{error&&<ErrorBox message={error}/>}{error.includes('erneut verbinden')&&<Link to='/api/auth/twitch/start' className='underline text-amber-300 text-sm'>Bitte Twitch erneut verbinden.</Link>}{ok&&<div className='text-emerald-300 text-sm'>{ok}</div>}
  <Card className='p-4 space-y-2'><h2 className='font-semibold'>Aktive Bans und Timeouts</h2>{active.length===0?<EmptyState title='Keine aktiven Maßnahmen' description='Aktuell sind keine Bans oder Timeouts aktiv.'/>
  :active.map((u:any)=><div key={`${u.userId}-${u.createdAt}`} className='rounded-lg border border-zinc-700 p-2 text-sm flex items-center justify-between gap-2'><div>{u.userName||u.userLogin||u.userId} · <StatusBadge status={u.type==='ban'?'ban':'timeout'} /> · <StatusBadge status={u.expiresAt&&new Date(u.expiresAt).getTime()<Date.now()?'expired':'active'} /></div><button className='rounded-lg border border-zinc-700 px-2 py-1' onClick={()=>{setForm({ ...form, userId:u.userId, username:u.userName||u.userLogin, action:'unban' }); setConfirmOpen(true);}}>Unban/Timeout entfernen</button></div>)}</Card>
  <Card className='p-4 space-y-2'><h2 className='font-semibold'>Manuelle Moderationsaktion</h2><input className='w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2' placeholder='User-ID' value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}/><input className='w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2' placeholder='Username' value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><select className='w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2' value={form.action} onChange={e=>setForm({...form,action:e.target.value})}><option value='timeout'>Timeout</option><option value='ban'>Ban</option><option value='unban'>Unban</option></select>{form.action==='timeout'&&<input type='number' className='w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2' value={form.durationSeconds} onChange={e=>setForm({...form,durationSeconds:e.target.value})}/>}<input maxLength={500} className='w-full rounded-lg border border-zinc-700 bg-zinc-900 px-3 py-2' placeholder='Grund (optional, max. 500)' value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className='rounded-lg bg-indigo-600 px-3 py-2 text-sm' onClick={()=>void submit()}>Aktion ausführen</button></Card>
  <Card className='p-4 space-y-2'><h2 className='font-semibold'>Moderationshistorie</h2>{actions.length===0?<EmptyState title='Keine Historie' description='Noch keine Moderationsaktionen geloggt.'/>:actions.map((a:any)=><div key={a.id} className='text-sm'>{new Date(a.createdAt).toLocaleString()} · <StatusBadge status={a.actionType||'unknown'} /> · {a.targetUsername || a.targetExternalUserId || '-'} · {a.reason || '-'}</div>)}</Card>
  <ConfirmDialog open={confirmOpen} title='Moderationsaktion bestätigen' description='Diese Aktion wird direkt auf Twitch ausgeführt.' confirmLabel='Bestätigen' onCancel={()=>setConfirmOpen(false)} onConfirm={async()=>{setConfirmOpen(false); await run();}}/>
  </div>; }
