import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useParams } from 'react-router-dom';
import { apiDelete, apiGet, apiPatch, apiPost } from '../api/client';
import Button from '../components/ui/Button';
import Card from '../components/ui/Card';
import EmptyState from '../components/ui/EmptyState';
import ErrorBox from '../components/ui/ErrorBox';
import LoadingState from '../components/ui/LoadingState';
import PageHeader from '../components/ui/PageHeader';

type Timer = { id: string; name: string; message: string; intervalMinutes: number; enabled: boolean };
const emptyForm = { name: '', message: '', intervalMinutes: 10, enabled: true };
export default function TimersPage(){const { channelId='' }=useParams(); const [items,setItems]=useState<Timer[]>([]); const [form,setForm]=useState(emptyForm); const [editingId,setEditingId]=useState<string|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [formError,setFormError]=useState('');
const validation=useMemo(()=>{if(!/^[a-z0-9_-]{1,32}$/.test(form.name))return 'Name ungültig.'; if(!form.message.trim())return 'Message erforderlich.'; if(form.message.length>500)return 'Message max 500 Zeichen.'; if(form.intervalMinutes<1||!Number.isInteger(form.intervalMinutes))return 'Intervall muss Ganzzahl >=1 sein.'; return '';},[form]);
const load=async()=>{setLoading(true);setError('');try{setItems(await apiGet(`/api/channels/${channelId}/timers`));}catch(e:any){setError(e?.data?.detail??e?.data?.error??'Timer konnten nicht geladen werden.');}finally{setLoading(false);}}; useEffect(()=>{void load();},[channelId]);
const save=async(e:FormEvent)=>{e.preventDefault(); setFormError(''); if(validation){setFormError(validation);return;} try{ if(editingId) await apiPatch(`/api/channels/${channelId}/timers/${editingId}`,form); else await apiPost(`/api/channels/${channelId}/timers`,form); setEditingId(null); setForm(emptyForm); await load();}catch(err:any){setFormError(err?.data?.detail??err?.data?.error??'Speichern fehlgeschlagen.');}};
return <div className='space-y-4'><PageHeader title='Timer' subtitle='Wiederkehrende Chat-Nachrichten verwalten (MVP-Execution abhängig vom Worker-Status).' />{error&&<ErrorBox message={error}/>}<Card className='p-4'><form onSubmit={save} className='grid md:grid-cols-2 gap-3'><input className='bg-zinc-900 border border-zinc-700 rounded px-2 py-2' placeholder='Name' value={form.name} onChange={(e)=>setForm({...form,name:e.target.value.toLowerCase()})}/><input className='bg-zinc-900 border border-zinc-700 rounded px-2 py-2' type='number' min={1} value={form.intervalMinutes} onChange={(e)=>setForm({...form,intervalMinutes:Number(e.target.value)})}/><textarea className='bg-zinc-900 border border-zinc-700 rounded px-2 py-2 md:col-span-2' value={form.message} onChange={(e)=>setForm({...form,message:e.target.value})}/><label><input type='checkbox' checked={form.enabled} onChange={(e)=>setForm({...form,enabled:e.target.checked})}/> Enabled</label><div className='md:col-span-2 flex gap-2'><Button>{editingId?'Timer speichern':'Timer erstellen'}</Button>{editingId&&<Button type='button' variant='ghost' onClick={()=>{setEditingId(null);setForm(emptyForm);}}>Abbrechen</Button>}</div>{(formError||validation)&&<div className='md:col-span-2'><ErrorBox message={formError||validation}/></div>}</form></Card>{loading?<LoadingState label='Timer laden…'/>:items.length===0?<EmptyState title='Keine Timer vorhanden' description='Lege den ersten Timer an, um regelmäßige Hinweise im Chat zu posten.'/>:<Card className='p-0 overflow-x-auto'><table className='w-full text-sm'><thead><tr><th className='p-2 text-left'>Name</th><th className='p-2 text-left'>Message</th><th className='p-2'>Intervall</th><th className='p-2'>Enabled</th><th className='p-2'>Aktion</th></tr></thead><tbody>{items.map((item)=><tr key={item.id} className='border-t border-zinc-800'><td className='p-2'>{item.name}</td><td className='p-2 max-w-xl truncate'>{item.message}</td><td className='p-2 text-center'>{item.intervalMinutes}m</td><td className='p-2 text-center'><input type='checkbox' checked={item.enabled} onChange={async(e)=>{await apiPatch(`/api/channels/${channelId}/timers/${item.id}`,{enabled:e.target.checked}); await load();}}/></td><td className='p-2 space-x-2'><Button variant='ghost' onClick={()=>{setEditingId(item.id);setForm(item);}}>Bearbeiten</Button><Button variant='danger' onClick={async()=>{if(!window.confirm('Timer löschen?'))return; await apiDelete(`/api/channels/${channelId}/timers/${item.id}`); await load();}}>Löschen</Button></td></tr>)}</tbody></table></Card>}</div>}
