import { Navigate, Outlet, Route, Routes } from 'react-router-dom';
import ProtectedRoute, { isSystemAdmin } from './components/ProtectedRoute'; import ChannelRoleGuard from './components/ChannelRoleGuard';
import { useAuth } from './auth/AuthProvider'; import AppShell from './layouts/AppShell'; import ChannelDashboardLayout from './layouts/ChannelDashboardLayout';
import LoginPage from './pages/LoginPage'; import LogsPage from './pages/LogsPage'; import SetupPage from './pages/SetupPage'; import ChannelSelectPage from './pages/ChannelSelectPage'; import DashboardHome from './pages/DashboardHome'; import CommandsPage from './pages/CommandsPage'; import TimersPage from './pages/TimersPage'; import CommunityPage from './pages/CommunityPage'; import RecapsPage from './pages/RecapsPage'; import CampaignsPage from './pages/CampaignsPage'; import ModerationPage from './pages/ModerationPage'; import IntegrationsPage from './pages/IntegrationsPage'; import SettingsPage from './pages/SettingsPage'; import AdminHealth from './pages/admin/AdminHealth'; import AdminTwitch from './pages/admin/AdminTwitch';
import LiveChatPage from './pages/LiveChatPage'; import ChattersPage from './pages/ChattersPage';
import ErrorBoundary from './components/ErrorBoundary';
import AdminHome from './pages/admin/AdminHome';
import AdminUsers from './pages/admin/AdminUsers';
import AdminChannels from './pages/admin/AdminChannels';
import AdminLayout from './layouts/AdminLayout';
const Home=()=>{const {user,loading}=useAuth(); if(loading)return null; if(!user)return <Navigate to='/login' replace/>; if (isSystemAdmin(user.role)) return <Navigate to='/admin' replace/>; if (!user.channels?.length) return <Navigate to='/setup' replace/>; return <Navigate to={user.channels.length===1?`/dashboard/channels/${user.channels[0].channelId}`:'/dashboard/channels'} replace/>};
const ChannelShell=()=> <ProtectedRoute><ChannelRoleGuard><ChannelDashboardLayout><Outlet/></ChannelDashboardLayout></ChannelRoleGuard></ProtectedRoute>;
const AdminRoute = ({ children }: any) => { const { user } = useAuth(); if (!isSystemAdmin(user?.role)) return <Navigate to='/' replace />; return children; };
export default function App(){return <AppShell><ErrorBoundary><Routes><Route path='/' element={<Home/>}/><Route path='/setup' element={<SetupPage/>}/><Route path='/login' element={<LoginPage/>}/><Route path='/channels' element={<Navigate to='/dashboard/channels' replace/>}/><Route path='/dashboard/channels' element={<ProtectedRoute><ChannelSelectPage/></ProtectedRoute>}/><Route path='/dashboard/channels/:channelId' element={<ChannelShell/>}><Route index element={<DashboardHome/>}/><Route path='commands' element={<CommandsPage/>}/><Route path='timers' element={<TimersPage/>}/><Route path='community' element={<CommunityPage/>}/><Route path='recaps' element={<RecapsPage/>}/><Route path='campaigns' element={<CampaignsPage/>}/><Route path='moderation' element={<ModerationPage/>}/><Route path='integrations' element={<IntegrationsPage/>}/><Route path='settings' element={<SettingsPage/>}/><Route path='logs' element={<LogsPage/>}/><Route path='live-chat' element={<LiveChatPage/>}/><Route path='chatters' element={<ChattersPage/>}/></Route><Route path='/admin' element={<ProtectedRoute><AdminRoute><AdminLayout/></AdminRoute></ProtectedRoute>}><Route index element={<AdminHome/>}/><Route path='users' element={<AdminUsers/>}/><Route path='streamers' element={<AdminChannels/>}/><Route path='twitch' element={<AdminTwitch/>}/><Route path='health' element={<AdminHealth/>}/><Route path='settings' element={<div className='p-6'>Admin Settings</div>}/></Route><Route path='*' element={<Navigate to='/' replace/>}/></Routes></ErrorBoundary></AppShell>}
